version: '3.1'
services:
  nuxt:
    build: 
      context: .
      dockerfile: Dockerfile
    image: nuxt
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: "node .output/server/index.mjs"

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt

  mysql:
    image: mysql:8.0.36
    restart: always
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
    external: false