name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IP_ADDRESS: ${{secrets.IP_ADDRESS}}
          USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          # Create the private key file
          echo -T "$SSH_PRIVATE_KEY" > privatekey.pem
          sudo chmod 700 privatekey.pem
          ssh -T -i privatekey.pem ubuntu@ec2-3-145-119-241.us-east-2.compute.amazonaws.com
          git pull
