name: Deploy to E2C

on:
  push:
    branches: [ "main" ]

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes from github
        run: |
          result=$(ls)
          echo "Command result: $result"